name: client
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  adaptive_breakpoints: ^0.1.0
  animations: ^2.0.0
  google_fonts: ^2.2.0
  google_sign_in: '^5.2.4'
  firebase_core: ^1.13.0
  firebase_auth: ^3.3.9
  # firebase_auth_oauth: ^1.1.0
  # github_sign_in: ^0.0.4
  # galileo_auth_oauth2: ^3.0.0
  # oauth2_client: ^2.3.2
  url_launcher: ^6.0.20
  provider: ^6.0.1
  # url_launcher: ^6.0.20
  uni_links: ^0.5.1
  flutter_svg: ^1.0.3
  cloud_firestore: ^3.1.10
  flutterfire_ui: ^0.3.5+1
  http: ^0.13.4
  twitter_login: ^4.0.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/